---
abstract: unknown
author:
  - '扶凯 <iakuf@163.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-KossyValidator
no_index:
  directory:
    - t
    - inc
requires:
  Hash::MultiValue: 0
  Mojolicious: 3.0
  Test::More: 0
version: 0.01
